// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dropper_service/dropper.proto

package dropper_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / A struct describing a file item to be updated on the target.
type FileItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / File destination path
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// / File contents (bytes)
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	// / File Permissions
	Permissions uint32 `protobuf:"varint,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// / File owner (user id)
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// / File group (group id)
	Group string `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	// / Shell command to run on file change
	Command string `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *FileItem) Reset() {
	*x = FileItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropper_service_dropper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileItem) ProtoMessage() {}

func (x *FileItem) ProtoReflect() protoreflect.Message {
	mi := &file_dropper_service_dropper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileItem.ProtoReflect.Descriptor instead.
func (*FileItem) Descriptor() ([]byte, []int) {
	return file_dropper_service_dropper_proto_rawDescGZIP(), []int{0}
}

func (x *FileItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileItem) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *FileItem) GetPermissions() uint32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

func (x *FileItem) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *FileItem) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FileItem) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// / A watch request, parameters are derived from client identity.
type WatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropper_service_dropper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dropper_service_dropper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_dropper_service_dropper_proto_rawDescGZIP(), []int{1}
}

// / A message sent from the watch stream.
type WatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / The possible message types sent during a watch session.
	//
	// Types that are assignable to Op:
	//
	//	*WatchResponse_Sync
	//	*WatchResponse_Update
	//	*WatchResponse_Remove
	Op isWatchResponse_Op `protobuf_oneof:"op"`
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropper_service_dropper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dropper_service_dropper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_dropper_service_dropper_proto_rawDescGZIP(), []int{2}
}

func (m *WatchResponse) GetOp() isWatchResponse_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *WatchResponse) GetSync() *WatchResponse_OpSync {
	if x, ok := x.GetOp().(*WatchResponse_Sync); ok {
		return x.Sync
	}
	return nil
}

func (x *WatchResponse) GetUpdate() *WatchResponse_OpUpdate {
	if x, ok := x.GetOp().(*WatchResponse_Update); ok {
		return x.Update
	}
	return nil
}

func (x *WatchResponse) GetRemove() *WatchResponse_OpRemove {
	if x, ok := x.GetOp().(*WatchResponse_Remove); ok {
		return x.Remove
	}
	return nil
}

type isWatchResponse_Op interface {
	isWatchResponse_Op()
}

type WatchResponse_Sync struct {
	Sync *WatchResponse_OpSync `protobuf:"bytes,1,opt,name=sync,proto3,oneof"`
}

type WatchResponse_Update struct {
	Update *WatchResponse_OpUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type WatchResponse_Remove struct {
	Remove *WatchResponse_OpRemove `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*WatchResponse_Sync) isWatchResponse_Op() {}

func (*WatchResponse_Update) isWatchResponse_Op() {}

func (*WatchResponse_Remove) isWatchResponse_Op() {}

// / Sent when the client has reconnected or fallen behind.
// / Contains the whole list of files.
type WatchResponse_OpSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*FileItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *WatchResponse_OpSync) Reset() {
	*x = WatchResponse_OpSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropper_service_dropper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse_OpSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse_OpSync) ProtoMessage() {}

func (x *WatchResponse_OpSync) ProtoReflect() protoreflect.Message {
	mi := &file_dropper_service_dropper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse_OpSync.ProtoReflect.Descriptor instead.
func (*WatchResponse_OpSync) Descriptor() ([]byte, []int) {
	return file_dropper_service_dropper_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WatchResponse_OpSync) GetItems() []*FileItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// / Sent when a single file entry has been updated.
type WatchResponse_OpUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *FileItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *WatchResponse_OpUpdate) Reset() {
	*x = WatchResponse_OpUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropper_service_dropper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse_OpUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse_OpUpdate) ProtoMessage() {}

func (x *WatchResponse_OpUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_dropper_service_dropper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse_OpUpdate.ProtoReflect.Descriptor instead.
func (*WatchResponse_OpUpdate) Descriptor() ([]byte, []int) {
	return file_dropper_service_dropper_proto_rawDescGZIP(), []int{2, 1}
}

func (x *WatchResponse_OpUpdate) GetItem() *FileItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// / Sent when a single file entry has been removed.
type WatchResponse_OpRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *WatchResponse_OpRemove) Reset() {
	*x = WatchResponse_OpRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropper_service_dropper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse_OpRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse_OpRemove) ProtoMessage() {}

func (x *WatchResponse_OpRemove) ProtoReflect() protoreflect.Message {
	mi := &file_dropper_service_dropper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse_OpRemove.ProtoReflect.Descriptor instead.
func (*WatchResponse_OpRemove) Descriptor() ([]byte, []int) {
	return file_dropper_service_dropper_proto_rawDescGZIP(), []int{2, 2}
}

func (x *WatchResponse_OpRemove) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_dropper_service_dropper_proto protoreflect.FileDescriptor

var file_dropper_service_dropper_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x76, 0x31, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x0e, 0x0a,
	0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd0, 0x02,
	0x0a, 0x0d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x35, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x48, 0x00,
	0x52, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x3b, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72,
	0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x4f, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x76, 0x31, 0x2e,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x70,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x1a, 0x33, 0x0a, 0x06, 0x4f, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x72, 0x6f, 0x70,
	0x70, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x33, 0x0a, 0x08, 0x4f, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x1e, 0x0a, 0x08, 0x4f, 0x70,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x70,
	0x32, 0x4e, 0x0a, 0x0e, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x64, 0x72,
	0x6f, 0x70, 0x70, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x76, 0x31,
	0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x77, 0x65, 0x6c, 0x63, 0x68, 0x30, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dropper_service_dropper_proto_rawDescOnce sync.Once
	file_dropper_service_dropper_proto_rawDescData = file_dropper_service_dropper_proto_rawDesc
)

func file_dropper_service_dropper_proto_rawDescGZIP() []byte {
	file_dropper_service_dropper_proto_rawDescOnce.Do(func() {
		file_dropper_service_dropper_proto_rawDescData = protoimpl.X.CompressGZIP(file_dropper_service_dropper_proto_rawDescData)
	})
	return file_dropper_service_dropper_proto_rawDescData
}

var file_dropper_service_dropper_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dropper_service_dropper_proto_goTypes = []interface{}{
	(*FileItem)(nil),               // 0: dropperv1.FileItem
	(*WatchRequest)(nil),           // 1: dropperv1.WatchRequest
	(*WatchResponse)(nil),          // 2: dropperv1.WatchResponse
	(*WatchResponse_OpSync)(nil),   // 3: dropperv1.WatchResponse.OpSync
	(*WatchResponse_OpUpdate)(nil), // 4: dropperv1.WatchResponse.OpUpdate
	(*WatchResponse_OpRemove)(nil), // 5: dropperv1.WatchResponse.OpRemove
}
var file_dropper_service_dropper_proto_depIdxs = []int32{
	3, // 0: dropperv1.WatchResponse.sync:type_name -> dropperv1.WatchResponse.OpSync
	4, // 1: dropperv1.WatchResponse.update:type_name -> dropperv1.WatchResponse.OpUpdate
	5, // 2: dropperv1.WatchResponse.remove:type_name -> dropperv1.WatchResponse.OpRemove
	0, // 3: dropperv1.WatchResponse.OpSync.items:type_name -> dropperv1.FileItem
	0, // 4: dropperv1.WatchResponse.OpUpdate.item:type_name -> dropperv1.FileItem
	1, // 5: dropperv1.DropperService.Watch:input_type -> dropperv1.WatchRequest
	2, // 6: dropperv1.DropperService.Watch:output_type -> dropperv1.WatchResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dropper_service_dropper_proto_init() }
func file_dropper_service_dropper_proto_init() {
	if File_dropper_service_dropper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dropper_service_dropper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropper_service_dropper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropper_service_dropper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropper_service_dropper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchResponse_OpSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropper_service_dropper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchResponse_OpUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropper_service_dropper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchResponse_OpRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dropper_service_dropper_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*WatchResponse_Sync)(nil),
		(*WatchResponse_Update)(nil),
		(*WatchResponse_Remove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dropper_service_dropper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dropper_service_dropper_proto_goTypes,
		DependencyIndexes: file_dropper_service_dropper_proto_depIdxs,
		MessageInfos:      file_dropper_service_dropper_proto_msgTypes,
	}.Build()
	File_dropper_service_dropper_proto = out.File
	file_dropper_service_dropper_proto_rawDesc = nil
	file_dropper_service_dropper_proto_goTypes = nil
	file_dropper_service_dropper_proto_depIdxs = nil
}
